name: Maven Central
on:
  workflow_dispatch:

jobs:
  main:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: java setup and gradle caching
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: decode key
        run: |
          echo "${{secrets.SIGNING_KEYFILE_BASE64}}" > ~/key.gpg.b64
          base64 -d ~/key.gpg.b64 > ~/key.gpg
          echo "SIGNING_KEYFILE=$(echo ~/key.gpg)" >> $GITHUB_ENV

      - name: assemble release
        run: ./gradlew aars

      - name: publish to maven central
        run: ./gradlew publishToSonatype #closeSonatypeStagingRepository
        env:
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}